/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppSettingsUsersRouteImport } from './routes/_app.settings.users'
import { Route as AppSettingsLocationsRouteImport } from './routes/_app.settings.locations'
import { Route as AppSettingsIntegrationsRouteImport } from './routes/_app.settings.integrations'
import { Route as AppSettingsAlertsRouteImport } from './routes/_app.settings.alerts'
import { Route as AppPlantQualityRouteImport } from './routes/_app.plant.quality'
import { Route as AppPlantProductionRouteImport } from './routes/_app.plant.production'
import { Route as AppPlantMaintenanceRouteImport } from './routes/_app.plant.maintenance'
import { Route as AppPlantEquipmentRouteImport } from './routes/_app.plant.equipment'
import { Route as AppNetworkScenariosRouteImport } from './routes/_app.network.scenarios'
import { Route as AppNetworkPlaybackRouteImport } from './routes/_app.network.playback'
import { Route as AppNetworkMapRouteImport } from './routes/_app.network.map'
import { Route as AppNetworkCompareRouteImport } from './routes/_app.network.compare'
import { Route as AppLogisticsShipmentsRouteImport } from './routes/_app.logistics.shipments'
import { Route as AppLogisticsRoutesRouteImport } from './routes/_app.logistics.routes'
import { Route as AppLogisticsCarriersRouteImport } from './routes/_app.logistics.carriers'
import { Route as AppInventoryTransfersRouteImport } from './routes/_app.inventory.transfers'
import { Route as AppInventoryStockRouteImport } from './routes/_app.inventory.stock'
import { Route as AppInventoryOrdersRouteImport } from './routes/_app.inventory.orders'
import { Route as AppInventoryAlertsRouteImport } from './routes/_app.inventory.alerts'
import { Route as AppAnalyticsReportsRouteImport } from './routes/_app.analytics.reports'
import { Route as AppAnalyticsIntelligenceRouteImport } from './routes/_app.analytics.intelligence'
import { Route as AppAnalyticsCostRouteImport } from './routes/_app.analytics.cost'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsUsersRoute = AppSettingsUsersRouteImport.update({
  id: '/settings/users',
  path: '/settings/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsLocationsRoute = AppSettingsLocationsRouteImport.update({
  id: '/settings/locations',
  path: '/settings/locations',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIntegrationsRoute = AppSettingsIntegrationsRouteImport.update({
  id: '/settings/integrations',
  path: '/settings/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsAlertsRoute = AppSettingsAlertsRouteImport.update({
  id: '/settings/alerts',
  path: '/settings/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppPlantQualityRoute = AppPlantQualityRouteImport.update({
  id: '/plant/quality',
  path: '/plant/quality',
  getParentRoute: () => AppRoute,
} as any)
const AppPlantProductionRoute = AppPlantProductionRouteImport.update({
  id: '/plant/production',
  path: '/plant/production',
  getParentRoute: () => AppRoute,
} as any)
const AppPlantMaintenanceRoute = AppPlantMaintenanceRouteImport.update({
  id: '/plant/maintenance',
  path: '/plant/maintenance',
  getParentRoute: () => AppRoute,
} as any)
const AppPlantEquipmentRoute = AppPlantEquipmentRouteImport.update({
  id: '/plant/equipment',
  path: '/plant/equipment',
  getParentRoute: () => AppRoute,
} as any)
const AppNetworkScenariosRoute = AppNetworkScenariosRouteImport.update({
  id: '/network/scenarios',
  path: '/network/scenarios',
  getParentRoute: () => AppRoute,
} as any)
const AppNetworkPlaybackRoute = AppNetworkPlaybackRouteImport.update({
  id: '/network/playback',
  path: '/network/playback',
  getParentRoute: () => AppRoute,
} as any)
const AppNetworkMapRoute = AppNetworkMapRouteImport.update({
  id: '/network/map',
  path: '/network/map',
  getParentRoute: () => AppRoute,
} as any)
const AppNetworkCompareRoute = AppNetworkCompareRouteImport.update({
  id: '/network/compare',
  path: '/network/compare',
  getParentRoute: () => AppRoute,
} as any)
const AppLogisticsShipmentsRoute = AppLogisticsShipmentsRouteImport.update({
  id: '/logistics/shipments',
  path: '/logistics/shipments',
  getParentRoute: () => AppRoute,
} as any)
const AppLogisticsRoutesRoute = AppLogisticsRoutesRouteImport.update({
  id: '/logistics/routes',
  path: '/logistics/routes',
  getParentRoute: () => AppRoute,
} as any)
const AppLogisticsCarriersRoute = AppLogisticsCarriersRouteImport.update({
  id: '/logistics/carriers',
  path: '/logistics/carriers',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryTransfersRoute = AppInventoryTransfersRouteImport.update({
  id: '/inventory/transfers',
  path: '/inventory/transfers',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryStockRoute = AppInventoryStockRouteImport.update({
  id: '/inventory/stock',
  path: '/inventory/stock',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryOrdersRoute = AppInventoryOrdersRouteImport.update({
  id: '/inventory/orders',
  path: '/inventory/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryAlertsRoute = AppInventoryAlertsRouteImport.update({
  id: '/inventory/alerts',
  path: '/inventory/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsReportsRoute = AppAnalyticsReportsRouteImport.update({
  id: '/analytics/reports',
  path: '/analytics/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsIntelligenceRoute =
  AppAnalyticsIntelligenceRouteImport.update({
    id: '/analytics/intelligence',
    path: '/analytics/intelligence',
    getParentRoute: () => AppRoute,
  } as any)
const AppAnalyticsCostRoute = AppAnalyticsCostRouteImport.update({
  id: '/analytics/cost',
  path: '/analytics/cost',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/analytics/cost': typeof AppAnalyticsCostRoute
  '/analytics/intelligence': typeof AppAnalyticsIntelligenceRoute
  '/analytics/reports': typeof AppAnalyticsReportsRoute
  '/inventory/alerts': typeof AppInventoryAlertsRoute
  '/inventory/orders': typeof AppInventoryOrdersRoute
  '/inventory/stock': typeof AppInventoryStockRoute
  '/inventory/transfers': typeof AppInventoryTransfersRoute
  '/logistics/carriers': typeof AppLogisticsCarriersRoute
  '/logistics/routes': typeof AppLogisticsRoutesRoute
  '/logistics/shipments': typeof AppLogisticsShipmentsRoute
  '/network/compare': typeof AppNetworkCompareRoute
  '/network/map': typeof AppNetworkMapRoute
  '/network/playback': typeof AppNetworkPlaybackRoute
  '/network/scenarios': typeof AppNetworkScenariosRoute
  '/plant/equipment': typeof AppPlantEquipmentRoute
  '/plant/maintenance': typeof AppPlantMaintenanceRoute
  '/plant/production': typeof AppPlantProductionRoute
  '/plant/quality': typeof AppPlantQualityRoute
  '/settings/alerts': typeof AppSettingsAlertsRoute
  '/settings/integrations': typeof AppSettingsIntegrationsRoute
  '/settings/locations': typeof AppSettingsLocationsRoute
  '/settings/users': typeof AppSettingsUsersRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AppIndexRoute
  '/analytics/cost': typeof AppAnalyticsCostRoute
  '/analytics/intelligence': typeof AppAnalyticsIntelligenceRoute
  '/analytics/reports': typeof AppAnalyticsReportsRoute
  '/inventory/alerts': typeof AppInventoryAlertsRoute
  '/inventory/orders': typeof AppInventoryOrdersRoute
  '/inventory/stock': typeof AppInventoryStockRoute
  '/inventory/transfers': typeof AppInventoryTransfersRoute
  '/logistics/carriers': typeof AppLogisticsCarriersRoute
  '/logistics/routes': typeof AppLogisticsRoutesRoute
  '/logistics/shipments': typeof AppLogisticsShipmentsRoute
  '/network/compare': typeof AppNetworkCompareRoute
  '/network/map': typeof AppNetworkMapRoute
  '/network/playback': typeof AppNetworkPlaybackRoute
  '/network/scenarios': typeof AppNetworkScenariosRoute
  '/plant/equipment': typeof AppPlantEquipmentRoute
  '/plant/maintenance': typeof AppPlantMaintenanceRoute
  '/plant/production': typeof AppPlantProductionRoute
  '/plant/quality': typeof AppPlantQualityRoute
  '/settings/alerts': typeof AppSettingsAlertsRoute
  '/settings/integrations': typeof AppSettingsIntegrationsRoute
  '/settings/locations': typeof AppSettingsLocationsRoute
  '/settings/users': typeof AppSettingsUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/': typeof AppIndexRoute
  '/_app/analytics/cost': typeof AppAnalyticsCostRoute
  '/_app/analytics/intelligence': typeof AppAnalyticsIntelligenceRoute
  '/_app/analytics/reports': typeof AppAnalyticsReportsRoute
  '/_app/inventory/alerts': typeof AppInventoryAlertsRoute
  '/_app/inventory/orders': typeof AppInventoryOrdersRoute
  '/_app/inventory/stock': typeof AppInventoryStockRoute
  '/_app/inventory/transfers': typeof AppInventoryTransfersRoute
  '/_app/logistics/carriers': typeof AppLogisticsCarriersRoute
  '/_app/logistics/routes': typeof AppLogisticsRoutesRoute
  '/_app/logistics/shipments': typeof AppLogisticsShipmentsRoute
  '/_app/network/compare': typeof AppNetworkCompareRoute
  '/_app/network/map': typeof AppNetworkMapRoute
  '/_app/network/playback': typeof AppNetworkPlaybackRoute
  '/_app/network/scenarios': typeof AppNetworkScenariosRoute
  '/_app/plant/equipment': typeof AppPlantEquipmentRoute
  '/_app/plant/maintenance': typeof AppPlantMaintenanceRoute
  '/_app/plant/production': typeof AppPlantProductionRoute
  '/_app/plant/quality': typeof AppPlantQualityRoute
  '/_app/settings/alerts': typeof AppSettingsAlertsRoute
  '/_app/settings/integrations': typeof AppSettingsIntegrationsRoute
  '/_app/settings/locations': typeof AppSettingsLocationsRoute
  '/_app/settings/users': typeof AppSettingsUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/analytics/cost'
    | '/analytics/intelligence'
    | '/analytics/reports'
    | '/inventory/alerts'
    | '/inventory/orders'
    | '/inventory/stock'
    | '/inventory/transfers'
    | '/logistics/carriers'
    | '/logistics/routes'
    | '/logistics/shipments'
    | '/network/compare'
    | '/network/map'
    | '/network/playback'
    | '/network/scenarios'
    | '/plant/equipment'
    | '/plant/maintenance'
    | '/plant/production'
    | '/plant/quality'
    | '/settings/alerts'
    | '/settings/integrations'
    | '/settings/locations'
    | '/settings/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/analytics/cost'
    | '/analytics/intelligence'
    | '/analytics/reports'
    | '/inventory/alerts'
    | '/inventory/orders'
    | '/inventory/stock'
    | '/inventory/transfers'
    | '/logistics/carriers'
    | '/logistics/routes'
    | '/logistics/shipments'
    | '/network/compare'
    | '/network/map'
    | '/network/playback'
    | '/network/scenarios'
    | '/plant/equipment'
    | '/plant/maintenance'
    | '/plant/production'
    | '/plant/quality'
    | '/settings/alerts'
    | '/settings/integrations'
    | '/settings/locations'
    | '/settings/users'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/'
    | '/_app/analytics/cost'
    | '/_app/analytics/intelligence'
    | '/_app/analytics/reports'
    | '/_app/inventory/alerts'
    | '/_app/inventory/orders'
    | '/_app/inventory/stock'
    | '/_app/inventory/transfers'
    | '/_app/logistics/carriers'
    | '/_app/logistics/routes'
    | '/_app/logistics/shipments'
    | '/_app/network/compare'
    | '/_app/network/map'
    | '/_app/network/playback'
    | '/_app/network/scenarios'
    | '/_app/plant/equipment'
    | '/_app/plant/maintenance'
    | '/_app/plant/production'
    | '/_app/plant/quality'
    | '/_app/settings/alerts'
    | '/_app/settings/integrations'
    | '/_app/settings/locations'
    | '/_app/settings/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/users': {
      id: '/_app/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AppSettingsUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/locations': {
      id: '/_app/settings/locations'
      path: '/settings/locations'
      fullPath: '/settings/locations'
      preLoaderRoute: typeof AppSettingsLocationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/integrations': {
      id: '/_app/settings/integrations'
      path: '/settings/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof AppSettingsIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/alerts': {
      id: '/_app/settings/alerts'
      path: '/settings/alerts'
      fullPath: '/settings/alerts'
      preLoaderRoute: typeof AppSettingsAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plant/quality': {
      id: '/_app/plant/quality'
      path: '/plant/quality'
      fullPath: '/plant/quality'
      preLoaderRoute: typeof AppPlantQualityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plant/production': {
      id: '/_app/plant/production'
      path: '/plant/production'
      fullPath: '/plant/production'
      preLoaderRoute: typeof AppPlantProductionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plant/maintenance': {
      id: '/_app/plant/maintenance'
      path: '/plant/maintenance'
      fullPath: '/plant/maintenance'
      preLoaderRoute: typeof AppPlantMaintenanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plant/equipment': {
      id: '/_app/plant/equipment'
      path: '/plant/equipment'
      fullPath: '/plant/equipment'
      preLoaderRoute: typeof AppPlantEquipmentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/network/scenarios': {
      id: '/_app/network/scenarios'
      path: '/network/scenarios'
      fullPath: '/network/scenarios'
      preLoaderRoute: typeof AppNetworkScenariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/network/playback': {
      id: '/_app/network/playback'
      path: '/network/playback'
      fullPath: '/network/playback'
      preLoaderRoute: typeof AppNetworkPlaybackRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/network/map': {
      id: '/_app/network/map'
      path: '/network/map'
      fullPath: '/network/map'
      preLoaderRoute: typeof AppNetworkMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/network/compare': {
      id: '/_app/network/compare'
      path: '/network/compare'
      fullPath: '/network/compare'
      preLoaderRoute: typeof AppNetworkCompareRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/logistics/shipments': {
      id: '/_app/logistics/shipments'
      path: '/logistics/shipments'
      fullPath: '/logistics/shipments'
      preLoaderRoute: typeof AppLogisticsShipmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/logistics/routes': {
      id: '/_app/logistics/routes'
      path: '/logistics/routes'
      fullPath: '/logistics/routes'
      preLoaderRoute: typeof AppLogisticsRoutesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/logistics/carriers': {
      id: '/_app/logistics/carriers'
      path: '/logistics/carriers'
      fullPath: '/logistics/carriers'
      preLoaderRoute: typeof AppLogisticsCarriersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/transfers': {
      id: '/_app/inventory/transfers'
      path: '/inventory/transfers'
      fullPath: '/inventory/transfers'
      preLoaderRoute: typeof AppInventoryTransfersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/stock': {
      id: '/_app/inventory/stock'
      path: '/inventory/stock'
      fullPath: '/inventory/stock'
      preLoaderRoute: typeof AppInventoryStockRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/orders': {
      id: '/_app/inventory/orders'
      path: '/inventory/orders'
      fullPath: '/inventory/orders'
      preLoaderRoute: typeof AppInventoryOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/alerts': {
      id: '/_app/inventory/alerts'
      path: '/inventory/alerts'
      fullPath: '/inventory/alerts'
      preLoaderRoute: typeof AppInventoryAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics/reports': {
      id: '/_app/analytics/reports'
      path: '/analytics/reports'
      fullPath: '/analytics/reports'
      preLoaderRoute: typeof AppAnalyticsReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics/intelligence': {
      id: '/_app/analytics/intelligence'
      path: '/analytics/intelligence'
      fullPath: '/analytics/intelligence'
      preLoaderRoute: typeof AppAnalyticsIntelligenceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics/cost': {
      id: '/_app/analytics/cost'
      path: '/analytics/cost'
      fullPath: '/analytics/cost'
      preLoaderRoute: typeof AppAnalyticsCostRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppAnalyticsCostRoute: typeof AppAnalyticsCostRoute
  AppAnalyticsIntelligenceRoute: typeof AppAnalyticsIntelligenceRoute
  AppAnalyticsReportsRoute: typeof AppAnalyticsReportsRoute
  AppInventoryAlertsRoute: typeof AppInventoryAlertsRoute
  AppInventoryOrdersRoute: typeof AppInventoryOrdersRoute
  AppInventoryStockRoute: typeof AppInventoryStockRoute
  AppInventoryTransfersRoute: typeof AppInventoryTransfersRoute
  AppLogisticsCarriersRoute: typeof AppLogisticsCarriersRoute
  AppLogisticsRoutesRoute: typeof AppLogisticsRoutesRoute
  AppLogisticsShipmentsRoute: typeof AppLogisticsShipmentsRoute
  AppNetworkCompareRoute: typeof AppNetworkCompareRoute
  AppNetworkMapRoute: typeof AppNetworkMapRoute
  AppNetworkPlaybackRoute: typeof AppNetworkPlaybackRoute
  AppNetworkScenariosRoute: typeof AppNetworkScenariosRoute
  AppPlantEquipmentRoute: typeof AppPlantEquipmentRoute
  AppPlantMaintenanceRoute: typeof AppPlantMaintenanceRoute
  AppPlantProductionRoute: typeof AppPlantProductionRoute
  AppPlantQualityRoute: typeof AppPlantQualityRoute
  AppSettingsAlertsRoute: typeof AppSettingsAlertsRoute
  AppSettingsIntegrationsRoute: typeof AppSettingsIntegrationsRoute
  AppSettingsLocationsRoute: typeof AppSettingsLocationsRoute
  AppSettingsUsersRoute: typeof AppSettingsUsersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppAnalyticsCostRoute: AppAnalyticsCostRoute,
  AppAnalyticsIntelligenceRoute: AppAnalyticsIntelligenceRoute,
  AppAnalyticsReportsRoute: AppAnalyticsReportsRoute,
  AppInventoryAlertsRoute: AppInventoryAlertsRoute,
  AppInventoryOrdersRoute: AppInventoryOrdersRoute,
  AppInventoryStockRoute: AppInventoryStockRoute,
  AppInventoryTransfersRoute: AppInventoryTransfersRoute,
  AppLogisticsCarriersRoute: AppLogisticsCarriersRoute,
  AppLogisticsRoutesRoute: AppLogisticsRoutesRoute,
  AppLogisticsShipmentsRoute: AppLogisticsShipmentsRoute,
  AppNetworkCompareRoute: AppNetworkCompareRoute,
  AppNetworkMapRoute: AppNetworkMapRoute,
  AppNetworkPlaybackRoute: AppNetworkPlaybackRoute,
  AppNetworkScenariosRoute: AppNetworkScenariosRoute,
  AppPlantEquipmentRoute: AppPlantEquipmentRoute,
  AppPlantMaintenanceRoute: AppPlantMaintenanceRoute,
  AppPlantProductionRoute: AppPlantProductionRoute,
  AppPlantQualityRoute: AppPlantQualityRoute,
  AppSettingsAlertsRoute: AppSettingsAlertsRoute,
  AppSettingsIntegrationsRoute: AppSettingsIntegrationsRoute,
  AppSettingsLocationsRoute: AppSettingsLocationsRoute,
  AppSettingsUsersRoute: AppSettingsUsersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
